
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT LRUID NUMBER HOSTNAME NEIGHBORNAME HOSTPORT NEIGHBORPORT COMMA SEMICOLON EQUALblock  : block monitoring\n                      | block comment\n                      | monitoring\n                      | commentcomment : COMMENTmonitoring : id_host COMMA id_neighbor COMMA id_hostPort COMMA id_neighborPort SEMICOLONid_host : HOSTNAME EQUAL LRUID id_neighbor : NEIGHBORNAME EQUAL LRUID id_hostPort : HOSTPORT EQUAL NUMBER id_neighborPort : NEIGHBORPORT EQUAL NUMBER'
    
_lr_action_items = {'COMMENT':([0,1,2,3,5,7,8,24,],[5,5,-3,-4,-5,-1,-2,-6,]),'HOSTNAME':([0,1,2,3,5,7,8,24,],[6,6,-3,-4,-5,-1,-2,-6,]),'$end':([1,2,3,5,7,8,24,],[0,-3,-4,-5,-1,-2,-6,]),'COMMA':([4,11,13,16,18,23,],[9,14,-7,19,-8,-9,]),'EQUAL':([6,12,17,22,],[10,15,20,25,]),'NEIGHBORNAME':([9,],[12,]),'LRUID':([10,15,],[13,18,]),'HOSTPORT':([14,],[17,]),'NEIGHBORPORT':([19,],[22,]),'NUMBER':([20,25,],[23,26,]),'SEMICOLON':([21,26,],[24,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'block':([0,],[1,]),'monitoring':([0,1,],[2,7,]),'comment':([0,1,],[3,8,]),'id_host':([0,1,],[4,4,]),'id_neighbor':([9,],[11,]),'id_hostPort':([14,],[16,]),'id_neighborPort':([19,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> block","S'",1,None,None,None),
  ('block -> block monitoring','block',2,'p_block','modelGenerator.py',135),
  ('block -> block comment','block',2,'p_block','modelGenerator.py',136),
  ('block -> monitoring','block',1,'p_block','modelGenerator.py',137),
  ('block -> comment','block',1,'p_block','modelGenerator.py',138),
  ('comment -> COMMENT','comment',1,'p_comment','modelGenerator.py',142),
  ('monitoring -> id_host COMMA id_neighbor COMMA id_hostPort COMMA id_neighborPort SEMICOLON','monitoring',8,'p_monitoring','modelGenerator.py',146),
  ('id_host -> HOSTNAME EQUAL LRUID','id_host',3,'p_id_host','modelGenerator.py',152),
  ('id_neighbor -> NEIGHBORNAME EQUAL LRUID','id_neighbor',3,'p_id_neighbor','modelGenerator.py',156),
  ('id_hostPort -> HOSTPORT EQUAL NUMBER','id_hostPort',3,'p_id_hostPort','modelGenerator.py',160),
  ('id_neighborPort -> NEIGHBORPORT EQUAL NUMBER','id_neighborPort',3,'p_id_neighborPort','modelGenerator.py',164),
]
